on:
  push:
    branches:
      - development
name: 🚀 Deploy development website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: osmo.digital
        username: pilates-boutique-dev@osmo.digital
        password: ${{ secrets.development_ftp_password }}
        server-dir: wp-content/themes/pilates-boutique/
        exclude: |
          **/node_modules/**
          package-lock.json
          package.json
          README.md
