on:
  push:
    branches:
      - staging
name: 🚀 Deploy staging website
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ossark.ie
        username: stagingdeploy@ossark.ie
        password: ${{ secrets.staging_ftp_password }}
        server-dir: wp-content/themes/ossark/
        exclude: |
          **/node_modules/**
          package-lock.json
          package.json
          README.md
          yarn.lock
          .editorconfig
          webpack.config.js
          .gitignore
          .github
          .git
          **/config/**
